### ISSUE TITLE
Problems with Subset leaving Image

### ISSUE THREAD

**Issue by swalkin** [dicengine/dice#23] opened 2016-01-26 18:21 UTC
HI,
I have noticed that if the a small portion of the part that you are tracking leaves the field of view/ image then dice will crash.  This is a minor issue so don't spend to much time on it.  
Thanks

**Comment by dicengine** [comment] 2016-02-08 21:11
This seems to be related to an issue in an older version of DICe. I ran some test cases with parts leaving the image boundary and could not reproduce the issue so I'm closing it.

**Closed by dicengine** 2016-02-08 21:11 UTC
