### ISSUE TITLE
Error reading images created with ImageJ

### ISSUE THREAD

**Issue by Prosofs** [dicengine/dice#117] opened 2019-04-30 13:59 UTC
Hi!
I'm having a trouble when trying to compile DICe. The message pops-up:

**DICe execution failed (see console for details)**

**_The console:_**
--- Input read successfully ---

C:\Users\dzturne\Software\trilinos\packages\teuchos\parameterlist\src\Teuchos_FileInputStream.cpp:53:

Throw number = 1

Throw test that evaluated to true: file_ == NULL

FileInputStream ctor failed to open file: C:\Users\LABEST01\Desktop\Prosofs\TESE\Ensaios\DINÂMICOS\DICe\ENSAIO--1009_43\params.xml

I already reinstalled DICe, and when this error occurs, I can't even compile the Example images...
Can you please help me?

Kind regards!

**Comment by Prosofs** [comment] 2019-04-30 14:36
Well... I reinstalled DICe again, and the first compilation I had was the example. It run ok. So I used the same working directory but with my images. Then the error ocurred:

**_The console:_**
--- List of images constructed successfuly ---

Image dimensions: 0 x 0
Output will be written to one file per frame with all subsets included
Execution information will be written to a separate file (not placed in the output headers)
C:\Users\dzturne\Software\DICe_nightly\src\base\DICe_ImageSerial.cpp:132:

Throw number = 2

Throw test that evaluated to true: true

Error, image file read failure


The image dimension 0x0 is odd, which is very strange ... because I was able to run these images like a month ago.. Just don't know what is happening. I once tried to make an .avi video from these .tiff images using ImageJ. Maybe this process corrupted the files.

Kind regards!

**Comment by dicengine** [comment] 2019-04-30 15:45
My guess is that the images are corrupt (especially if it seems the example problems run okay). It could be that the ImageJ process didn't create the right header info for the .tif file. You could try reading and saving the .tif images in another program and trying DICe again.

**Comment by Prosofs** [comment] 2019-04-30 18:27
It seems to be that the problems were ocurring always at that same folder (dont ask me why lol). I read and saved the .tif images with Matlab, ImageJ and Photron FASTCAM Viewer and it worked. The only difference is that I made all the process in a new folder with a different path location. I'm glad that I had the back-up files of the original video

Thanks for the reply!

**Comment by dicengine** [comment] 2019-04-30 18:29
Sounds like the issue is resolved so I'll close it. Let me know if this is not the case.

**Closed by dicengine** 2019-04-30 18:29 UTC

**Comment by Prosofs** [comment] 2019-04-30 18:31
You can close it, thank you

**Comment by wyh123456987** [comment] 2024-03-12 02:23
Hi!
I also had this problem when trying to compile DICe. The message pops-up:

DICe execution failed (see console for details)

The console:
-- Input read successfully ---

C:\Users\dzturne\Software\trilinos\packages\teuchos\parameterlist\src\Teuchos_FileInputStream.cpp:53:

Throw number = 1

Throw test that evaluated to true: file_ == NULL

FileInputStream ctor failed to open file: C:\Users\吴以航\dice_working_dir\params.xml

I already reinstalled DICe, and when this error occurs, I can't even compile the Example images...
Can you please help me?

Kind regards!

**Comment by dicengine** [comment] 2024-03-12 12:23
In your case, it could be the non-ASCII characters in the file path. Have you tried using an all-english characters file path for the location of the images?
